AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestrutura automatizada com EC2

Resources:

  MinhaInstancia:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-00e801948462f718a